/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ble_packet_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f166a243918c52ef2c3d883dc65d9f2e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sic/ble_packet_sink.h>
// pydoc.h is automatically generated in the build directory
#include <ble_packet_sink_pydoc.h>

void bind_ble_packet_sink(py::module& m)
{

    using ble_packet_sink = ::gr::sic::ble_packet_sink;


    py::class_<ble_packet_sink,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ble_packet_sink>>(m, "ble_packet_sink", D(ble_packet_sink))

        .def(py::init(&ble_packet_sink::make),
             py::arg("base_address"),
             py::arg("preamble_threshold"),
             py::arg("lfsr"),
             py::arg("block_id"),
             D(ble_packet_sink, make))


        ;
}
