/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(periodic_message_source.h) */
/* BINDTOOL_HEADER_FILE_HASH(dc0b08c1e761590d4324d286e9b83c3f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sic/periodic_message_source.h>
// pydoc.h is automatically generated in the build directory
#include <periodic_message_source_pydoc.h>

void bind_periodic_message_source(py::module& m)
{

    using periodic_message_source = ::gr::sic::periodic_message_source;


    py::class_<periodic_message_source,
               gr::block,
               gr::basic_block,
               std::shared_ptr<periodic_message_source>>(
        m, "periodic_message_source", D(periodic_message_source))

        .def(py::init(&periodic_message_source::make),
             py::arg("message"),
             py::arg("period_ms"),
             py::arg("n_messages"),
             D(periodic_message_source, make))


        ;
}
