/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tag_aligner.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c53653cec70aedbd8b711015fd315f3d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sic/tag_aligner.h>
// pydoc.h is automatically generated in the build directory
#include <tag_aligner_pydoc.h>

void bind_tag_aligner(py::module& m)
{

    using tag_aligner = ::gr::sic::tag_aligner;


    py::class_<tag_aligner, gr::block, gr::basic_block, std::shared_ptr<tag_aligner>>(
        m, "tag_aligner", D(tag_aligner))

        .def(py::init(&tag_aligner::make),
             py::arg("sps"),
             py::arg("type_size_high"),
             D(tag_aligner, make))


        .def("sps", &tag_aligner::sps, D(tag_aligner, sps))


        .def("set_sps", &tag_aligner::set_sps, py::arg("sps"), D(tag_aligner, set_sps))

        ;
}
