/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(transmission_enabler.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b11a02998c1d0138831c354bd95b9d83)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sic/transmission_enabler.h>
// pydoc.h is automatically generated in the build directory
#include <transmission_enabler_pydoc.h>

void bind_transmission_enabler(py::module& m)
{

    using transmission_enabler = ::gr::sic::transmission_enabler;


    py::class_<transmission_enabler,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<transmission_enabler>>(
        m, "transmission_enabler", D(transmission_enabler))

        .def(py::init(&transmission_enabler::make),
             py::arg("block_size"),
             D(transmission_enabler, make))


        ;
}
