/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ieee802154_packet_sink.h) */
/* BINDTOOL_HEADER_FILE_HASH(2a694d43aa9cda11fa6f6d8a096619fc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ble/ieee802154_packet_sink.h>
// pydoc.h is automatically generated in the build directory
#include <ieee802154_packet_sink_pydoc.h>

void bind_ieee802154_packet_sink(py::module& m)
{

    using ieee802154_packet_sink = ::gr::ble::ieee802154_packet_sink;


    py::class_<ieee802154_packet_sink,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ieee802154_packet_sink>>(
        m, "ieee802154_packet_sink", D(ieee802154_packet_sink))

        .def(py::init(&ieee802154_packet_sink::make),
             py::arg("preamble_threshold"),
             py::arg("crc_included"),
             py::arg("block_id"),
             D(ieee802154_packet_sink, make))


        ;
}
