/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tag_iq_stream.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(193b25f0be8b4e52fbabc61cc549f973)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ble/tag_iq_stream.h>
// pydoc.h is automatically generated in the build directory
#include <tag_iq_stream_pydoc.h>

void bind_tag_iq_stream(py::module& m)
{

    using tag_iq_stream = ::gr::ble::tag_iq_stream;


    py::class_<tag_iq_stream, gr::block, gr::basic_block, std::shared_ptr<tag_iq_stream>>(
        m, "tag_iq_stream", D(tag_iq_stream))

        .def(py::init(&tag_iq_stream::make), py::arg("sps"), D(tag_iq_stream, make))


        ;
}
