/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tag_stream_from_message.h) */
/* BINDTOOL_HEADER_FILE_HASH(0a99aa3056c8fff21eba299d6a9b16f2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ble/tag_stream_from_message.h>
// pydoc.h is automatically generated in the build directory
#include <tag_stream_from_message_pydoc.h>

void bind_tag_stream_from_message(py::module& m)
{

    using tag_stream_from_message = ::gr::ble::tag_stream_from_message;


    py::class_<tag_stream_from_message,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<tag_stream_from_message>>(
        m, "tag_stream_from_message", D(tag_stream_from_message))

        .def(py::init(&tag_stream_from_message::make), D(tag_stream_from_message, make))


        ;
}
